AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: >-
          $.Resources.MyItemConsumer.Properties.Events.Trigger.Properties.EventBusName
        Message: Event bus name
        InputType: string
      - JSONPath: >-
          $.Resources.MyItemConsumer.Properties.Events.Trigger.Properties.Pattern.source.0
        Message: Set source
        InputType: string
      - JSONPath: >-
          $.Resources.MyItemConsumer.Properties.Events.Trigger.Properties.Pattern["detail-type"].0
        Message: Set detail-type
        InputType: string
    Placeholders:
      - Placeholder: MyItem
        message: Set value for 'MyItem' placeholder
Resources:
  MyItemConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: MyItemConsumer.handler
      Runtime: nodejs14.x
      Timeout: 3
      Policies:
        - S3WritePolicy: null
          BucketName: !Ref MyItemBucket
      Environment:
        Variables:
          MyItemBucket: !Ref MyItemBucket
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: custom-bus
            Pattern:
              source:
                - my-source
              detail-type:
                - my-detail-type
  MyItemBucket:
    Type: AWS::S3::Bucket
