AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: >-
          $.Resources.OrderEventConsumer.Properties.Events.OrderEvent.Properties.EventBusName
        Message: Set eventbus name
        InputType: string
      - JSONPath: >-
          $.Resources.OrderEventConsumer.Properties.Events.OrderEvent.Properties.Pattern.source.0
        Message: Set source
        InputType: string
      - JSONPath: >-
          $.Resources.OrderEventConsumer.Properties.Events.OrderEvent.Properties.Pattern["detail-type"].0
        Message: Set detail type
        InputType: string
    Placeholders:
      - Placeholder: Order
        message: Set value for 'Order' placeholder
Resources:
  OrderEventConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          DatabaseTable: !Ref Table
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref Table
      Events:
        OrderEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: custombus
            InputPath: $.detail
            Pattern:
              source:
                - order-service
              detail-type:
                - order-event
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
