AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: >-
          $.Resources.MyItemEventConsumer.Properties.Events.MyEvent.Properties.EventBusName
        Message: Set eventbus
        InputType: string
      - JSONPath: >-
          $.Resources.MyItemEventConsumer.Properties.Events.MyEvent.Properties.Pattern.source.0
        Message: Set source
        InputType: string
      - JSONPath: >-
          $.Resources.MyItemEventConsumer.Properties.Events.MyEvent.Properties.Pattern["detail-type"].0
        Message: Set detailtype
        InputType: string
    Placeholders:
      - Placeholder: MyItem
        message: Set value for 'MyItem' placeholder
Resources:
  MyItemEventConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: '10'
      Environment:
        Variables:
          DatabaseTable: !Ref Table
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref Table
      Events:
        MyEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: custombus
            Pattern:
              source:
                - order-service
              detail-type:
                - order-event
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
