AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: >-
          $.Resources.CartConsumer.Properties.Events.CartEvent.Properties.EventBusName
        Message: Set eventbus name
        InputType: string
      - JSONPath: >-
          $.Resources.CartConsumer.Properties.Events.CartEvent.Properties.Pattern.source.0
        Message: Set source
        InputType: string
      - JSONPath: >-
          $.Resources.CartConsumer.Properties.Events.CartEvent.Properties.Pattern["detail-type"].0
        Message: Set detail type
        InputType: string
    Placeholders:
      - Placeholder: Cart
        message: Set value for 'Cart' placeholder
      - Placeholder: Cart
        message: Set value for 'Cart' placeholder
Resources:
  CartConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          DatabaseTable: !Ref CartTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref CartTable
      Events:
        CartEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: commerce
            InputPath: $.detail.data.new
            Pattern:
              source:
                - ecom-cart-service
              detail-type:
                - CartEvent
  CartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
