AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties: []
    Placeholders:
      - Placeholder: ScheduledFunction
        message: Set value for 'ScheduledFunction' placeholder
Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ScheduledFunction.handler
      Runtime: nodejs14.x
      CodeUri: src/
      MemorySize: 128
      Timeout: 3
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Enabled: true
