AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    CodeUri: ./src
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 15
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: $.Globals.Function.CodeUri
        Message: ''
        InputType: string
    Placeholders:
      - Placeholder: HttpApi
        message: Set value for 'HttpApi' placeholder
      - Placeholder: LambdaFunction
        message: Set value for 'LambdaFunction' placeholder
Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref AppName
      Description: An Amazon API Gateway HTTP API and an AWS Lambda function.
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
      Target: !Sub >-
        arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}/invocations
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-function
      Handler: app.handler
      Environment:
        Variables:
          Variable1: 1234
          Variable2: ABCD
